apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: app1
  namespace: default
spec:
  releaseName: app1
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: nginx
    version: 8.9.1
  values:
    service:
      type: ClusterIP
      port: 8080
