# fluxcd/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# all clusters (environments)
resources:
- clusters/dev
- clusters/staging
- clusters/prod

# Additional infrastructure components
- infrastructure/monitoring
- infrastructure/networking
- infrastructure/security
- infrastructure/namespaces

# Applications
- apps/app1
- apps/app2

# HelmReleases
- helm-releases
