apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubble-ui
  template:
    metadata:
      labels:
        app: hubble-ui
    spec:
      containers:
      - name: hubble-ui
        image: quay.io/cilium/hubble-ui:v0.8.0
        ports:
        - containerPort: 8081
